name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main
      uses: actions/checkout@v2

    - name: Build and deploy
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
